language: node_js
node_js:
    - node

branches:
    only:
        - production
script:
    - npm run build-prod

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: ./build/prod/
    keep_history: true
    on:
        branch: production
